### ISSUE TITLE
API Down

### ISSUE THREAD

**Issue by GrantBirki** [adamburgess/tarkov-time#36]
👋 Hey there! For sometime I have been using your API to get the real time in Tarkov with my Discord bot. However, it started returning errors today so I wanted to let you know.

This actually prompted me to re-write some of your code in Python so I no longer have to depend on external APIs, so thank you for documenting your code as I was able to easily adapt it! 😸 

For anyone coming to this repo and needing a Python function that gets the current time in Tarkov, you will find this useful: https://gist.github.com/GrantBirki/708a4de18d734502b2bbf85721d740f4

**Comment by adamburgess** [comment]
oh no I should totally have set up an alert on this haha, when I make changes I don't check the api as it was just a fun little thing tacked on to vercel's edge workers

will fix in the fullness of time!

**Comment by adamburgess** [comment]
Ok, this should be fixed. Couldn't fix the Vercel problem (rolling back to a previous version didn't fix it... so no clue... Vercel works well with nextjs and nothing else, go figure) so switched to Cloudflare Pages + Workers (which Vercel uses under the hood anyway)

DNS TTL is 1 day so might take a day to update. Even though you aren't using it anymore ;)

> so thank you for documenting your code as I was able to easily adapt it!

all good :)
