### ISSUE TITLE
time not correct

### ISSUE THREAD

**Issue by sick50g** [adamburgess/tarkov-time#42]
i guess how new wipe come time is not corrent on site and ingame

**Comment by adamburgess** [comment]
working for me. you sure your clock is synced? https://time.is/ will tell you if it has drifted.

**Comment by sick50g** [comment]
i was looking your time on site and watching time in game lobby and it
wasnt correct, like 20minutes diffrence

ned, 24. srp 2022. u 12:55 Adam Burgess ***@***.***> napisao
je:

**Comment by adamburgess** [comment]
so have you checked your system's clock sync? https://time.is/ 20 minutes difference would imply your computer's time is off by ~3 minutes...

If it is synced, let me know what browser you're using and your current timezone.

**Comment by sick50g** [comment]
https://prnt.sc/3C1DVRoI99YP

time zone is UTC+01:00 sarajevo, skopje, varshav and zagreb

ned, 24. srp 2022. u 14:50 Adam Burgess ***@***.***> napisao
je:

**Comment by sick50g** [comment]
my bad, when i refreshed time zone it was perfectly correct, sry for
wasting your time, have a nice day

ned, 24. srp 2022. u 14:55 Tony Hoxter ***@***.***> napisao je:

**Comment by adamburgess** [comment]
very peculiar... I'm happy it all works for now.

if you encounter this problem again, shoot me a message :)
