### ISSUE TITLE
Standalone app possible?

### ISSUE THREAD

**Issue by KongGal** [adamburgess/tarkov-time#44]
Would it be possible to make a standalone widget that only pretty much only show the 2 clocks that you could start and have run as an app on your pc? that way you could force it to be on top and could do other things while its there rather than having to have a full homepage there you have to tab back to all the time

![image](https://user-images.githubusercontent.com/5061152/183987725-9aa99f61-668f-439a-b821-286bd3d6c17a.png)
like if you could make a standalone app that just shows this maybe a new page with just that on it and then use electronjs to create a wrapper / Widget that loads that homepage and only display this little box?

**Comment by fmjensen** [comment]
I know this does not fully answer your question but... if you got an Elgato Stream deck then you can get Tarkov Time on a button using [this plugin](https://github.com/fmjensen/Stream-Deck-Tarkov-Time) that i wrote with heavy inspiration from here.

**Comment by adamburgess** [comment]
> ... electronjs ...

I'd rather not have a silly little program take up 100mb of ram :)

So I made it in rust using [druid](https://github.com/linebender/druid) UI framework

It looks like this:
![image](https://user-images.githubusercontent.com/7473960/184503822-57de6f71-5f62-4293-a793-4e1591ad30d1.png)
It doesn't stay on top... for now... and it has no icon... oh well...

If you have rust you can `cd desktop-app && cargo run` and it should all work fine.
Alternatively, download a pre-compiled 1.5mb exe from here: https://github.com/adamburgess/tarkov-time/releases/tag/1.0.0

**Comment by KongGal** [comment]
> > ... electronjs ...
> 
> I'd rather not have a silly little program take up 100mb of ram :)
> 
> So I made it in rust using [druid](https://github.com/linebender/druid) UI framework
> 
> It looks like this: ![image](https://user-images.githubusercontent.com/7473960/184503822-57de6f71-5f62-4293-a793-4e1591ad30d1.png) It doesn't stay on top... for now... and it has no icon... oh well...
> 
> If you have rust you can `cd desktop-app && cargo run` and it should all work fine. Alternatively, download a pre-compiled 1.5mb exe from here: https://github.com/adamburgess/tarkov-time/releases/tag/1.0.0

This is perfect! didn't know of druid :)

for others who might see this you can use something liek DeskPins to pin it and make it stay on top!

Thanks for creating this Adam!
