### ISSUE TITLE
I'm making too many requests

### ISSUE THREAD

**Issue by komorg123** [adamburgess/tarkov-time#53]
Hi! I have made a streamdeck plugin (https://apps.elgato.com/plugins/com.komordzsi.tarkovtime) that is using your API to show the current tarkov times. From today, I'm getting the following message from the API: "Sorry, you're making too many requests. Make an issue at github.com/adamburgess/tarkov-time" So thats why I'm creating this issue :)

Is it resolveable, or shouldn't I use your API for this?

**Comment by komorg123** [comment]
the plugin calls the API on startup and once every hour

**Comment by adamburgess** [comment]
nice, my message worked :) I've restored functionality

so, I use Cloudflare pages functions/workers to serve the API which gives a free limit of 100,000 requests per day, and someone (who I can only identify by their user agent including 'QtWebEngine', presumably you) is doing around 40,000 requests per day from all around the world. This wouldn't have been a problem but then yesterday someone else started to send 30,000 requests and now I am getting emails telling me I'm approaching the limit (which is hilaaarious, but also annoying if I was actually going to use CF workers for my own projects.)

So I've checked the logs and sure enough you are right, I am seeing 2 requests every hour (one to /left and one to /right, it would be great if you just used the [/api](https://tarkov-time.adam.id.au/api?type=plain))

So I guess your plugin is just that popular, congrats :)

>Is it resolveable, or shouldn't I use your API for this?

Well, hm, so you have three options:
1. Fork the repo and host it on your own CF pages, and then its _your_ quota that you're using ;)
1. Continue using my API, but use the /api endpoint which will cut the requests in half. This would probably be good even if you do the above.
1. The best way ideally is to not use my API, or any API. You can calculate the time fully client side, all you need is the logic in [time.ts](https://github.com/adamburgess/tarkov-time/blob/master/src/time.ts) - realTimeToTarkovTime. Should be easy to adapt.

**Comment by adamburgess** [comment]
sorry for the annoying message buttt there was no other way to get in contact! it would be great if you changed your client's user agent to something more identifyable 🌴

**Comment by komorg123** [comment]
Thank you!

I already implemented an offline version that use no network resource for the time calculation (used in OBS). I will change the plugin code tonight as well. I hope I caused no problem for you, and thank you for your kindness. I hope this traffic will disappear in the beginning of next week.

**Comment by adamburgess** [comment]
not a problem, I hope I didn't do too much damage to your plugin either.

I've rather enjoyed seeing insanely huge request counts on my analytics page :D
![image](https://user-images.githubusercontent.com/7473960/222396461-a5fa1798-4829-4b0d-b65b-a9ebc7fb3c3c.png)
(last 30 days)

**Comment by komorg123** [comment]
I updated the plugin (removed API call and do the time calculation by itself) and sent to elgato, Usually it takes 1-2 days to be released. Will let you know once it is done.

**Comment by komorg123** [comment]
Update is compleated on Elgato side. If you want, cut the line again (I dont know how long it takes to update all the clients, also not sure there is auto update feature...).
